spring.application.name=WaterLabsAI
server.port=8085

spring.ai.chat.client.enabled=true
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=nvidia/nemotron-3-ultra-550b-a55b:free
spring.ai.openai.api-key= #api-key
spring.main.allow-bean-definition-overriding=true

#logging
logging.level.org.springframework.ai=DEBUG
logging.level.com.openai=DEBUG
