name: WaterLabsAI CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./WaterLabsAI/ai

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: WaterLabsAI/ai/pom.xml

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test

      - name: Build Application
        run: ./mvnw package
      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: waterlabsai
          path: WaterLabsAI/ai/target/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/waterlabsai:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/waterlabsai:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/waterlabsai:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/waterlabsai:${{ github.sha }}
